services:
  backend:
    build: ./backend
    container_name: seenflix-backend
    env_file:
      - .env
    environment:
      - PORT=3000
      - DATABASE_URL=file:./prisma/dev.db
      # Les autres variables (JWT, TMDB_API_KEY) seront chargées depuis le fichier .env
    volumes:
      # Persistance de la base de données SQLite
      - ./backend/prisma/dev.db:/app/prisma/dev.db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: seenflix-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
